name: Fresh US. AIR
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23724
title: 'Garage Door Repair '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1377cd'
    - '#234560'
    - '#8c725d'
    - '#fa8221'
    - '#ffd38c'
  brandStrength: 1
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
