name: Fresh US. AIR
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5704126788768917
title: Air Duct Cleaning Services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd0000'
    - '#212121'
    - '#666666'
    - '#96eb00'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5593206831254065
  rhythmicContrast: 0.5012704015243798
purpose: []
